# Ubuntu 14.04 Trusty support
sudo: required
dist: bionic

language: cpp
sude: enabled

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
    - os: linux
     dist: bionic
     addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          packages:
            - clang-10
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang-10"
    - os: osx
      osx_image: xcode11.3
      env:
        - MATRIX_EVAL="CC=clang CXX=clang++"

before_install : 
    - eval "${MATRIX_EVAL}"

before_script:  
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug 

script: make && ctest -V
